=== lorenzotarragoni/CS-School/3-XML/sistemaPlanetario/sistemaPlanetario.dtd
<!ELEMENT GALASSIA   (SISTEMA_PLANETARIO *)>

<!ELEMENT SISTEMA_PLANETARIO ( PIANETA*, COMETA*, ASTEROIDE*)>

<!ATTLIST  NOME_STELLA  CDATA  #REQUIRED  TIPO_STELLA  CDATA  #REQUIRED>

<!ELEMENT  PIANETA  (LUNA*)>

<!ATTLIST  NOME_PIANETA CDATA  #REQUIRED RAGGIO_PIANETA CDATA #IMPLIED >

<!ELEMENT  LUNA  (#PCDATA) >

<!ELEMENT  COMETA  (#PCDATA) >

<!ELEMENT  ASTEROIDE  (#PCDATA) >

=== lorenzotarragoni/CS-School/3-XML/sistemaPlanetario/sistemaPlanetario.xml
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE GALASSIA SYSTEM "sistemaPlanetario.dtd">
    <GALASSIA>
        <SISTEMA_PLANETARIO NOME="Sistema Solare">
            <STELLA NOME_STELLA = "Sole" TIPO_STELLA = "G2V">
            </STELLA>
            <PIANETA NOME_PIANETA ="Mercurio" RAGGIO_PIANETA ="57.9 milioni di km">
                <LUNA>Luna</LUNA>
                <COMETA>K12</COMETA>
                <ASTEROIDE>Ceres</ASTEROIDE>
            </PIANETA>
            <PIANET NOME_PIANETAA ="Venere" RAGGIO_PIANETA ="108.2 milioni di km">
                <LUNA>Luna</LUNA>
                <COMETA>D45</COMETA>
                <ASTEROIDE>Pallas</ASTEROIDE>
            </PIANETA>
            <PIANETA NOME_PIANETA ="Terra" RAGGIO_PIANETA ="149.6 milioni di km">
                <LUNA>Luna</LUNA>
                <COMETA>F67</COMETA>
                <ASTEROIDE>Vesta</ASTEROIDE>
        </SISTEMA_PLANETARIO>
